name: Disruptor.NET CI

on:
    push:
        branches:
            - main
        tags-ignore:
            - '*' # Don't run on tag pushes

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Start Date
              id: mldisruptor_ci_startdate
              run: echo "mldisruptor_ci_startdate=$(date)" >> $GITHUB_OUTPUT

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0 # Fetch all history for tags

            - name: Install dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x.x'

            - name: Install Node.js v22.14.0
              uses: actions/setup-node@v3
              with:
                node-version: '22.14.0'

            - name: Install npm dependencies
              run:
                npm ci

            - name: Increment version and create tag
              id: versioning # Allows us to reference the output of this step
              run: npx tsx ./eng/lib/versioning.ts
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Restore ML Disruptor .NET
              run:
                npx tsx ./eng/tasks/restore.mldisruptor.net.task.ts

            - name: Build ML Disruptor .NET (${{ steps.versioning.outputs.version }})
              env:
                VERSION: ${{ steps.versioning.outputs.version }}
              run:
                npx tsx ./eng/tasks/build.mldisruptor.net.task.ts

            - name: Run ML Disruptor Tests
              run:
                npx tsx ./eng/tasks/test.mldisruptor.net.task.ts

            - name: Pipline Ending At
              run: |
                echo "Pipeline ending at $(date)"
                echo "Pipeline duration: $((($(date +%s) - $(date -d "${{ steps.mldisruptor_ci_startdate.outputs.mldisruptor_ci_startdate }}" +%s)) / 60)) minute(s)"