name: Disruptor.NET CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js v22.14.0
              uses: actions/setup-node@v3
              with:
                node-version: '22.14.0'

            - name: Install npm dependencies
              run:
                npm ci

            - name: Run .NET tests
              run:
                npx tsx ./eng/src-tests/packages/mldisruptor.net.tests.task.ts