name: Disruptor.NET CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x.x'

            - name: Install Node.js v22.14.0
              uses: actions/setup-node@v3
              with:
                node-version: '22.14.0'

            - name: Install npm dependencies
              run:
                npm ci

            - name: Run ML Disruptor Tests
              run:
                npx tsx ./eng/src-tests/packages/mldisruptor.net.tests.task.ts

            - name: Run ML Disruptor Performance Predictor Tests
              run:
                npx tsx ./eng/src-tests/packages/mldisruptor.net.performance-predictor.tests.task.ts