name: Tagged Disruptor.NET CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x.x'

            - name: Install Node.js v22.14.0
              uses: actions/setup-node@v3
              with:
                node-version: '22.14.0'

            - name: Install npm dependencies
              run:
                npm ci

            - name: Restore ML Disruptor .NET
              run:
                npx tsx ./eng/tasks/restore.mldisruptor.net.task.ts

            - name: Build ML Disruptor .NET
              run:
                npx tsx ./eng/tasks/build.mldisruptor.net.task.ts

            - name: Run ML Disruptor Tests
              run:
                npx tsx ./eng/tasks/test.mldisruptor.net.task.ts

            - name: Pipline Ending At
              run: |
                echo "Pipeline ending at $(date)"